#%RAML 1.0
types:
  milestone1-manoj:
    items:
      properties:
        id:
          example: "2482"
          type: string
        name:
          example: Kartik Kocchar
          type: string
        email:
          example: kartik_kocchar@rutherford.io
          type: string
        gender:
          example: female
          type: string
        status:
          example: inactive
          type: string
title: milestone 1
mediaType:
  - application/json
version: v1
protocols:
  - HTTP
/milestone1:
  get:
    responses:
      "200": {}
